language: node_js
node_js:
- '6.9.1'
sudo: false
cache:
  directories:
  - node_modules
script:
  - npm test
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t grommet/next-sample:latest .
  - docker push grommet/next-sample:latest